# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64]
        run-config:
          - { scheme: 'CI_macOS', destination: 'platform=macOS' }
          - { scheme: 'CI_iOS', destination: 'platform=iOS Simulator,OS=15.0,name=iPhone 13' }
    steps:
    - uses: actions/checkout@v3
    - name: Run tests for macOS
      run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme '${{ matrix.run-config['scheme'] }}' CODE_SIGN_IDENTITY="" CEDE_SIGN_REQUIRED=NO
   
    - uses: actions/checkout@v3
    - name: Run tests for iOS
      run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme '${{ matrix.run-config['scheme'] }}' CODE_SIGN_IDENTITY="" CEDE_SIGN_REQUIRED=NO
